b4solid/b4solid/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('', include('authentication.urls')),
    path('', include('administration.urls')),
    path('', include('shop.urls')),
    path('', include('payment.urls')),
    path('', include('request.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

b4solid/main/urls.py
from django.urls import include, path
from main.views import main

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
]

b4solid/payment/urls.py
from django.urls import include, path
from payment.views import cart, delete_order, checkout

app_name = 'payment'

urlpatterns = [
    path('cart/', cart, name='cart'),
    path('checkout', checkout, name='checkout'),
    path('delete_order/<int:id>', delete_order, name='delete_order')
]

b4solid/shop/urls.py
from django.urls import include, path
from shop.views import shop

app_name = 'shop'

urlpatterns = [
    path('shop/', shop, name='shop'),
]

b4solid/shop/views.py
import json
from turtle import up
from django.shortcuts import redirect, render
import requests as rq

def shop(request):

    if 'user' not in request.session:
        return redirect('authentication:login')

    if request.method == 'POST':
        request_data = {int(k):int(v) for k, v in request.POST.items() if k != 'csrfmiddlewaretoken' and v != '0'}

        for product_id, amount in request_data.items():
            if amount > 0:
                updated_order = {
                    'username': request.session['user'],
                    'productId': product_id,
                    'amount': amount
                }

                rq.post(
                    url='http://aldenluth.fi:8081/orders',
                    data=json.dumps(updated_order),
                    headers={'Content-Type': 'application/json'}
                )

        return redirect('shop:shop')

    products_all = rq.get('http://aldenluth.fi:8082/products').json()
    orders_all = rq.get('http://aldenluth.fi:8081/orders/' + request.session['user']).json()

    context = {}
    context['products'] = products_all
    context['orders'] = sum(x['amount'] for x in orders_all)

    for product in products_all:
        product['id_label'] = f'#{product["id"]:08X}'

    return render(request, 'shop.html', context=context)

b4solid/shop/templates/shop.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="h-screen flex flex-col items-center p-36">
  <p class="text-7xl font-bold">Buy Products</p>
  <div class="grid grid-cols-5 gap-8 py-20 w-full" method="post">
    {% for product in products %}
    <form class="bg-white p-4 rounded-md shadow-lg flex flex-col" method="post">
      {% csrf_token %}
      <img src="{{ product.imageLink }}" alt="{{ product.name }}" class="w-full h-64 object-cover mb-4">
      <h2 class="text-xl font-bold">{{ product.nama }}</h2>
      <p class="text-zinc-500">{{ product.deskripsi }}</p>
      <p class="text-zinc-700 font-bold mt-2">{{ product.harga }} IDR</p>
      <div class="flex justify-between items-end space-x-3">
        <button type="button"
          class="size-8 inline-flex justify-center items-center gap-x-2 text-sm font-medium rounded-md border border-gray-200 bg-indigo-600 text-white shadow-sm"
          data-hs-input-number-decrement="">
          <svg class="flex-shrink-0 size-3.5" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
            viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"
            stroke-linejoin="round">
            <path d="M5 12h14"></path>
          </svg>
        </button>
        <input type="number" name="{{ product.id }}"
          class="h-8 flex-grow border-zinc-400 border-2 rounded-md bg-zinc-100 mt-2 remove-arrow" min=0
          max="{{ product.stok }}" value="0">
        <button type="button"
          class="size-8 inline-flex justify-center items-center gap-x-2 text-sm font-medium rounded-md border border-gray-200 bg-indigo-600 text-white shadow-sm"
          data-hs-input-number-increment="">
          <svg class="flex-shrink-0 size-3.5" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
            viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"
            stroke-linejoin="round">
            <path d="M5 12h14"></path>
            <path d="M12 5v14"></path>
          </svg>
        </button>
      </div>
      <button type="submit" class="bg-indigo-600 text-white font-bold py-2 px-4 rounded-md mt-4">Add to Cart</button>
    </form>
    {% endfor %}
  </div>
</div>
<div class="flex justify-center">
  <footer class="bottom-5 fixed h-20 shadow-xl rounded-lg bg-zinc-50 w-1/4">
    <div class="justify-between w-full h-full flex items-center px-6">
      <p class="font-bold">You have {{ orders }} item/s in your cart</p>
      <a href="{% url 'payment:cart'  %}"" class="bg-indigo-600 text-white font-bold py-2 px-4 rounded-md">Go to Cart</a>
    </div>
  </footer>
</div>
</form>
<script>
  document.querySelectorAll('[data-hs-input-number-decrement]').forEach(function (decrementButton) {
    decrementButton.addEventListener('click', function () {
      var input = decrementButton.nextElementSibling;
      var value = parseInt(input.value, 10);
      if (value > 0) {
        input.value = value - 1;
      }
    });
  });

  document.querySelectorAll('[data-hs-input-number-increment]').forEach(function (incrementButton) {
    incrementButton.addEventListener('click', function () {
      var input = incrementButton.previousElementSibling;
      var value = parseInt(input.value, 10);
      if (value < parseInt(input.max, 10)) {
        input.value = value + 1;
      }
    });
  });
</script>
<style>
  .remove-arrow::-webkit-inner-spin-button,
  .remove-arrow::-webkit-outer-spin-button {
    -webkit-appearance: none;
    margin: 0;
  }

  .remove-arrow {
    -moz-appearance: textfield;
    appearance: textfield;
  }
</style>
{% endblock %}