b4solid/administration/urls.py
from django.urls import path
from administration.views import (requests,
                                  products,
                                  transactions,
                                  add_product,
                                  edit_product,
                                  vouchers,
                                  add_voucher,
                                  edit_voucher,
                                )

app_name = 'administration'

urlpatterns = [
    path('requests/', requests, name='requests'),
    path('products/', products, name='products'),
    path('vouchers/', vouchers, name='vouchers'),
    path('transactions/', transactions, name='transactions'),
    path('add_product/', add_product, name='add_product'),
    path('edit_product/<int:id>/', edit_product, name='edit_product'),
    path('add_voucher/', add_voucher, name='add_voucher'),
    path('edit_voucher/<int:id>/', edit_voucher, name='edit_voucher')
]

b4solid/b4solid/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('', include('authentication.urls')),
    path('', include('administration.urls')),
    path('', include('shop.urls')),
    path('', include('payment.urls')),
    path('', include('request.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

b4solid/main/urls.py
from django.urls import include, path
from main.views import main

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
]

b4solid/payment/urls.py
from django.urls import include, path
from payment.views import cart, delete_order, checkout

app_name = 'payment'

urlpatterns = [
    path('cart/', cart, name='cart'),
    path('checkout', checkout, name='checkout'),
    path('delete_order/<int:id>', delete_order, name='delete_order')
]

b4solid/request/urls.py
from django.urls import path
from request.views import user_requests, add_request, edit_request

app_name = 'request'

urlpatterns = [
    path('user_requests/', user_requests, name='user_requests'),
    path('add_request/', add_request, name='add_request'),
    path('edit_request/<int:id>/', edit_request, name='edit_request'),
]

b4solid/shop/urls.py
from django.urls import include, path
from shop.views import shop

app_name = 'shop'

urlpatterns = [
    path('shop/', shop, name='shop'),
]

b4solid/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>b4solid</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	{% tailwind_css %}
	<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
</head>

<body class="">
	<header class="fixed flex z-10 w-screen justify-center bg-white">
		{% include 'header.html' %}
	</header>

	{% block content %}
	{% endblock %}
</body>
<script>
	var message_ele = document.querySelector(".message");

	setTimeout(function () {
		message_ele.remove();
	}, 1000);
</script>

</html>

b4solid/templates/header.html
{% if request.session.user != None %}
<div class="flex justify-between items-center h-20 shadow-md w-full p-10">
    <a href="{% url 'main:main' %}" class="text-4xl font-bold">B4-solid</a>
    <div class="flex items-center space-x-8">
    {% if request.session.godmode %}
        <a href="{% url 'administration:requests' %}" class="font-bold">Requests</a>
        <a href="{% url 'administration:vouchers' %}" class="font-bold">Vouchers</a>
        <a href="{% url 'administration:products' %}" class="font-bold">Products</a>
        <a href="{% url 'administration:transactions' %}" class="font-bold">Transactions</a>
    {% else %}
        <a href="{% url 'payment:checkout' %}" class="font-bold">History</a>
        <a href="{% url 'shop:shop' %}" class="font-bold">Shop</a>
        <a href="{% url 'request:user_requests' %}" class="font-bold">Request</a>
    {% endif %}
        <a href="{% url 'authentication:logout' %}" class="text-red-400">Logout</a>
    </div>
</div>
{% endif %}