b4solid/administration/urls.py
from django.urls import path
from administration.views import (requests,
                                  products,
                                  transactions,
                                  add_product,
                                  edit_product,
                                  vouchers,
                                  add_voucher,
                                  edit_voucher,
                                )

app_name = 'administration'

urlpatterns = [
    path('requests/', requests, name='requests'),
    path('products/', products, name='products'),
    path('vouchers/', vouchers, name='vouchers'),
    path('transactions/', transactions, name='transactions'),
    path('add_product/', add_product, name='add_product'),
    path('edit_product/<int:id>/', edit_product, name='edit_product'),
    path('add_voucher/', add_voucher, name='add_voucher'),
    path('edit_voucher/<int:id>/', edit_voucher, name='edit_voucher')
]

b4solid/b4solid/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('', include('authentication.urls')),
    path('', include('administration.urls')),
    path('', include('shop.urls')),
    path('', include('payment.urls')),
    path('', include('request.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

b4solid/main/urls.py
from django.urls import include, path
from main.views import main

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
]

b4solid/request/urls.py
from django.urls import path
from request.views import user_requests, add_request, edit_request

app_name = 'request'

urlpatterns = [
    path('user_requests/', user_requests, name='user_requests'),
    path('add_request/', add_request, name='add_request'),
    path('edit_request/<int:id>/', edit_request, name='edit_request'),
]

b4solid/administration/views.py
import json
from django.shortcuts import redirect, render
from django.contrib import messages
import requests as rq

def requests(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if not request.session.get('godmode'):
        return redirect('main:main')

    if request.method == 'POST':
        req = rq.get('http://aldenluth.fi:8083/requests/' +
                     request.POST['id']).json()
        req["currency"] = "IDR"

        created_product = {
            "nama": req['name'],
            "harga": req['harga'],
            "deskripsi": req['deskripsi'],
            "stok": 1,
            "imageLink": req['imageLink']
        }

        if request.POST['action'] == 'approve':
            result = rq.post(
                url='http://aldenluth.fi:8082/products',
                data=json.dumps(created_product),
                headers={'Content-Type': 'application/json'}
            )

            result_dict = result.json()

            req['status'] = True
            req['productId'] = result_dict['id']

            result = rq.put(
                url='http://aldenluth.fi:8083/requests/' + request.POST['id'],
                data=json.dumps(req),
                headers={'Content-Type': 'application/json'}
            )

        elif request.POST['action'] == 'reject':
            req['status'] = False

            result = rq.put(
                url='http://aldenluth.fi:8083/requests/' + request.POST['id'],
                data=json.dumps(req),
                headers={'Content-Type': 'application/json'}
            )

    user_requests = rq.get('http://aldenluth.fi:8083/requests')
    user_requests = user_requests.json()

    context = {}
    context['requests'] = user_requests

    for req in user_requests:
        if req["productId"] is not None:
            req['product_label'] = f'#{req["productId"]:08X}'
        req['id_label'] = f'#{req["id"]:08X}'

    return render(request, 'requests.html', context=context)


def products(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if not request.session.get('godmode'):
        return redirect('main:main')

    if request.method == 'POST':
        rq.delete('http://aldenluth.fi:8082/products/' + request.POST['id'])

    products_all = rq.get('http://aldenluth.fi:8082/products').json()

    context = {}
    context['products'] = products_all

    for product in products_all:
        product['id_label'] = f'#{product["id"]:08X}'

    return render(request, 'products.html', context=context)


def add_product(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if not request.session.get('godmode'):
        return redirect('main:main')

    if request.method == 'POST':
        rq.post(
            url='http://aldenluth.fi:8082/products',
            data=json.dumps(request.POST),
            headers={'Content-Type': 'application/json'}
        )
        return redirect('administration:products')

    return render(request, 'add_product.html')


def edit_product(request, id):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if not request.session.get('godmode'):
        return redirect('main:main')

    if request.method == 'POST':
        rq.put(
            url='http://aldenluth.fi:8082/products/' + str(id),
            data=json.dumps(request.POST),
            headers={'Content-Type': 'application/json'}
        )
        return redirect('administration:products')

    product = rq.get('http://aldenluth.fi:8082/products/' + str(id)).json()
    product['id_label'] = f'#{product["id"]:08X}'

    context = {}
    context['product'] = product

    return render(request, 'edit_product.html', context=context)


def vouchers(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if not request.session.get('godmode'):
        return redirect('main:main')

    if request.method == 'POST':
        rq.delete('http://aldenluth.fi:8084/vouchers/' +
                  request.POST['voucherId'])

    vouchers_all = rq.get('http://aldenluth.fi:8084/vouchers').json()

    context = {}
    context['vouchers'] = vouchers_all

    for voucher in vouchers_all:
        voucher['id_label'] = f'#{voucher["voucherId"]:08X}'

    return render(request, 'vouchers.html', context=context)


def add_voucher(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if not request.session.get('godmode'):
        return redirect('main:main')

    if request.method == 'POST':
        result = rq.post(
            url='http://aldenluth.fi:8084/vouchers',
            data=json.dumps(request.POST),
            headers={'Content-Type': 'application/json'}
        )

        if result.status_code == 201:
            return redirect('administration:vouchers')
        else:
            messages.error(request, result.text)

    return render(request, 'add_voucher.html')


def edit_voucher(request, id):
    if 'user' not in request.session:
            return redirect('authentication:login')

    if not request.session.get('godmode'):
        return redirect('main:main')

    if request.method == 'POST':
        result = rq.put(
            url='http://aldenluth.fi:8084/vouchers/' + str(id),
            data=json.dumps(request.POST),
            headers={'Content-Type': 'application/json'}
        )
        if result.status_code == 200:
            return redirect('administration:vouchers')
        else:
            messages.error(request, result.text)

    voucher = rq.get('http://aldenluth.fi:8084/vouchers/' + str(id)).json()
    voucher['id_label'] = f'#{voucher["voucherId"]:08X}'

    context = {}
    context['voucher'] = voucher

    return render(request, 'edit_voucher.html', context=context)

def transactions(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if not request.session.get('godmode'):
        return redirect('main:main')

    if request.method == 'POST':

        transaction = rq.get("http://aldenluth.fi:8080/transactions/" + request.POST['transactionId']).json()
        transaction['status'] = request.POST['status']

        rq.put(
            url='http://aldenluth.fi:8080/transactions/' + request.POST['transactionId'],
            data=json.dumps(transaction),
            headers={'Content-Type': 'application/json'}
        )

    context = {}

    all_transactions = rq.get("http://aldenluth.fi:8080/transactions").json()
    context['transactions'] = all_transactions

    for transaction in all_transactions:
        transaction['id_label'] = f'#{transaction["id"]:08X}'
        transaction['voucher_label'] = f'#{transaction["voucherId"]:08X}' if transaction["voucherId"] else None

    return render(request, 'transactions_admin.html', context=context)

b4solid/request/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
import requests as rq
import json

def user_requests(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if request.method == 'POST':
        rq.delete('http://aldenluth.fi:8083/requests/' + request.POST['id'])

    user_requests = rq.get('http://aldenluth.fi:8083/requests/user/' + request.session['user'])
    user_requests = user_requests.json()

    context = {}
    context['requests'] = user_requests

    for req in user_requests:
        if req["productId"] is not None:
            req['product_label'] = f'#{req["productId"]:08X}'
        req['id_label'] = f'#{req["id"]:08X}'

    return render(request, 'user_requests.html', context=context)

def add_request(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if request.method == 'POST':
        updated_request = request.POST.copy()
        updated_request.update({'username': request.session['user']})

        rq.post(
            url='http://aldenluth.fi:8083/requests',
            data=json.dumps(updated_request),
            headers={'Content-Type': 'application/json'}
        )

        return redirect('request:user_requests')

    return render(request, 'add_request.html')

def edit_request(request, id):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if request.method == 'POST':
        updated_request = request.POST.copy()
        updated_request.update({'username': request.session['user']})

        rq.put(
            url='http://aldenluth.fi:8083/requests/' + str(id),
            data=json.dumps(updated_request),
            headers={'Content-Type': 'application/json'}
        )
        return redirect('request:user_requests')

    req = rq.get('http://aldenluth.fi:8083/requests/' + str(id)).json()
    req['id_label'] = f'#{req["id"]:08X}'

    context = {}
    context['req'] = req

    return render(request, 'edit_request.html', context=context)

b4solid/administration/templates/add_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="h-screen flex flex-col items-center justify-center">
  <div class="p-6 shadow-2xl rounded-xl flex flex-col items-center justify-center space-y-6 w-1/4">
    <div class="text-4xl font-bold">
      Add Product
    </div>
    <form method="post" class="flex flex-col w-full space-y-4">
      {% csrf_token %}
        <div class="flex flex-col space-y-1">
          <label for="nama" class="">Name</label>
          <input type="text" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="nama" placeholder="A Very Cool Product" required>
        </div>
        <div class="flex justify-between">
          <div class="flex flex-col space-y-1">
            <label for="harga" class="">Price</label>
            <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="harga" placeholder=0 required>
          </div>
          <div class="flex flex-col space-y-1">
            <label for="stok" class="">Stock</label>
            <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="stok" placeholder=0 required>
          </div>
        </div>
        <div class="flex flex-col space-y-1">
          <label for="deskripsi" class="">Description</label>
          <textarea class="border-zinc-400 border-2 rounded-md bg-zinc-100 h-40 resize-none" name="deskripsi" placeholder="Lorem ipsum..."></textarea>
        </div>
        <div class="flex flex-col space-y-1">
          <label for="imageLink" class="">Image URL</label>
          <input type="url" class="border-zinc-400 border-2 rounded-md bg-zinc-100" placeholder="https://example.com" name="imageLink">
        </div>
      <button class="bg-indigo-600 p-2 mt-8 rounded-md flex items-center justify-center font-bold text-white" type="submit">Add Product</button>
    </form>
  </div>
</div>
{% endblock %}

b4solid/administration/templates/add_voucher.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="h-screen flex flex-col items-center justify-center">
  <div class="p-6 shadow-2xl rounded-xl flex flex-col items-center justify-center space-y-6 w-1/4">
    <div class="text-4xl font-bold">
      Add Voucher
    </div>
    <form method="post" class="flex flex-col w-full space-y-4">
      {% csrf_token %}
      {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'error' %}
          <div class="bg-red-400 text-white p-2 rounded-md w-full text-center message">
            {{ message }}
          </div>
          {% endif %}
        {% endfor %}
      {% endif %}
        <div class="flex flex-col space-y-1">
          <label for="voucherName" class="">Name</label>
          <input type="text" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="voucherName" placeholder="A Very Valuable Voucher" required>
        </div>
        <div class="flex justify-between">
          <div class="flex flex-col space-y-1">
            <label for="discountAmount" class="">Discount Amount</label>
            <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="discountAmount" placeholder=0 required>
          </div>
          <div class="flex flex-col space-y-1">
            <label for="maxUsage" class="">Max Quota</label>
            <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="maxUsage" placeholder="No Limit">
          </div>
        </div>
      <button class="bg-indigo-600 p-2 mt-8 rounded-md flex items-center justify-center font-bold text-white" type="submit">Add Voucher</button>
    </form>
  </div>
</div>
{% endblock %}

b4solid/administration/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="h-screen flex flex-col items-center justify-center">
  <div class="p-6 shadow-2xl rounded-xl flex flex-col items-center justify-center space-y-6 w-1/4">
    <div class="text-4xl font-bold text-center">
      Product<br>{{ product.id_label }}
    </div>
    <form method="post" class="flex flex-col w-full space-y-4">
      {% csrf_token %}
        <div class="flex flex-col space-y-1">
          <label for="nama" class="">Name</label>
          <input type="text" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="nama" value="{{ product.nama }}" required>
        </div>
        <div class="flex justify-between">
          <div class="flex flex-col space-y-1">
            <label for="harga" class="">Price</label>
            <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="harga" value={{ product.harga }} required>
          </div>
          <div class="flex flex-col space-y-1">
            <label for="stok" class="">Stock</label>
            <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="stok" value={{ product.stok }} required>
          </div>
        </div>
        <div class="flex flex-col space-y-1">
          <label for="deskripsi" class="">Description</label>
          <textarea class="border-zinc-400 border-2 rounded-md bg-zinc-100 h-40 resize-none" name="deskripsi" >{{ product.deskripsi }}</textarea>
        </div>
        <div class="flex flex-col space-y-1">
          <label for="imageLink" class="">Image URL</label>
          <input type="url" class="border-zinc-400 border-2 rounded-md bg-zinc-100" placeholder="https://example.com" name="imageLink" value={{ product.imageLink }}>
        </div>
      <button class="bg-indigo-600 p-2 mt-8 rounded-md flex items-center justify-center font-bold text-white" type="submit">Edit Product</button>
    </form>
  </div>
</div>
{% endblock %}

b4solid/administration/templates/edit_voucher.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="h-screen flex flex-col items-center justify-center">
  <div class="p-6 shadow-2xl rounded-xl flex flex-col items-center justify-center space-y-6 w-1/4">
    <div class="text-4xl font-bold text-center">
      Voucher<br>{{ voucher.id_label }}
    </div>
    <form method="post" class="flex flex-col w-full space-y-4">
      {% csrf_token %}
      {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'error' %}
            <div class="bg-red-400 text-white p-2 rounded-md w-full text-center message">
              {{ message }}
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
      <div class="flex flex-col space-y-1">
        <label for="voucherName" class="">Name</label>
        <input type="text" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="voucherName" value="{{ voucher.voucherName }}"" required>
      </div>
      <div class="flex justify-between">
        <div class="flex flex-col space-y-1">
          <label for="discountAmount" class="">Discount Amount</label>
          <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="discountAmount" value={{ voucher.discountAmount }} required>
        </div>
        <div class="flex flex-col space-y-1">
          <label for="maxUsage" class="">Max Quota</label>
          <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="maxUsage" value={{ voucher.maxUsage }}>
        </div>
      </div>
      <button class="bg-indigo-600 p-2 mt-8 rounded-md flex items-center justify-center font-bold text-white" type="submit">Edit Voucher</button>
    </form>
  </div>
</div>
{% endblock %}

b4solid/administration/templates/products.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="h-screen flex flex-col items-center p-36">
  <p class="text-7xl font-bold">Manage Products</p>
  <div class="flex flex-col items-start mx-10 py-20 w-full space-y-4">
    <a href="{% url 'administration:add_product' %}" class="bg-indigo-600 text-white font-bold py-2 px-4 rounded-md">Add Product</a>
    <div class="rounded-md border-2 border-zinc-200 w-full">
      <table class="w-full divide-y divide-zinc-200 table-fixed">
        <thead>
          <tr>
            <th scope="col" class="px-6 py-3 text-start font-bold w-28">ID</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-72">Name</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-28">Price</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-84">Description</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-24">Stock</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-80">Image</th>
            <th scope="col" colspan=2 class="px-6 py-3 text-center font-bold w-40">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
          <tr class="border-t-2 ">
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ product.id_label }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ product.nama }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ product.harga }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">
              {% if product.deskripsi %}
              {{ product.deskripsi }}
              {% else %}
              <span>-</span>
              {% endif %}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ product.stok }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">
              {% if product.imageLink %}
              <a class="text-indigo-600 underline" href="{{ product.imageLink }}">{{ product.imageLink }}</a>
              {% else %}
              <span>-</span>
              {% endif %}
            </td>
            <td class="py-4 whitespace-nowrap text-center text-sm font-medium">
              <a href="{% url 'administration:edit_product' product.id %}"
                class="inline-flex items-center py-2 px-4 text-sm font-bold bg-indigo-600 rounded-md text-white disabled:opacity-50 disabled:pointer-events-none">Edit</a>
            </td>
            <td class="py-4 whitespace-nowrap text-center text-sm font-medium">
              <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="id" value={{ product.id }}>
                <button type="submit" class="inline-flex items-center text-sm font-bold text-red-400 rounded-md disabled:opacity-50 disabled:pointer-events-none">Delete</button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

b4solid/administration/templates/requests.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="h-screen flex flex-col items-center p-36">
  <p class="text-7xl font-bold">Manage Requests</p>
  <div class="flex flex-col items-start mx-10 py-20 w-full space-y-4">
    <div class="rounded-md border-2 border-zinc-200 w-full">
      <table class="w-full divide-y divide-zinc-200 table-fixed">
        <thead>
          <tr>
            <th scope="col" class="px-6 py-3 text-start font-bold w-32">ID</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-36">Product ID</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-32">User</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-40">Name</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-36">Price in IDR</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-40">Description</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-32">Store Link</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-32">Image</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-20">Currency</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-28">Status</th>
            <th scope="col" colspan=2 class="px-6 py-3 text-center font-bold w-48">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for req in requests %}
          <tr class="border-t-2 ">
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ req.id_label }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">
              {% if req.productId %}
                {{ req.product_label }}
              {% else %}
                <span>-</span>
              {% endif %}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ req.username }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ req.name }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ req.harga }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">
              {% if req.deskripsi %}
                {{ req.deskripsi }}
              {% else %}
                <span>-</span>
              {% endif %}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis text-indigo-600 underline"><a href="{{ req.storeLink }}">{{ req.storeLink }}</a></td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">
              {% if req.imageLink %}
                <a class="text-indigo-600 underline" href="{{ product.imageLink }}">{{ req.imageLink }}</a>
              {% else %}
                <span>-</span>
              {% endif %}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">{{ req.currency }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">
              {% if req.status == None %}
              <span class="text-yellow-400">Pending</span>
              {% elif req.status == True %}
              <span class="text-emerald-400">Approved</span>
              {% else %}
              <span class="text-red-400">Rejected</span>
              {% endif %}
            </td>
            <td class="py-4 whitespace-nowrap text-center text-sm font-medium">
              {% if req.status == None %}
              <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="id" value={{ req.id }}>
                <input type="hidden" name="action" value="approve">
                <button type="submit" class="inline-flex py-2 px-4 items-center text-sm font-bold bg-emerald-600 rounded-md text-white disabled:opacity-50 disabled:pointer-events-none">Approve</button>
              </form>
              {% endif %}
            </td>
            <td class="py-4 whitespace-nowrap text-center text-sm font-medium">
              {% if req.status == None %}
              <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="id" value={{ req.id }}>
                <input type="hidden" name="action" value="reject">
                <button type="submit" class="inline-flex py-2 px-4 items-center text-sm font-bold bg-red-400 rounded-md text-white disabled:opacity-50 disabled:pointer-events-none">Reject</button>
              </form>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

b4solid/administration/templates/vouchers.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="h-screen flex flex-col items-center py-36 px-96">
  <p class="text-7xl font-bold">Manage Vouchers</p>
  <div class="flex flex-col items-start py-20 w-full space-y-4">
    <a href="{% url 'administration:add_voucher' %}" class="bg-indigo-600 text-white font-bold py-2 px-4 rounded-md">Add Voucher</a>
    <div class="rounded-md border-2 border-zinc-200 w-full">
      <table class="w-full divide-y divide-zinc-200 table-fixed">
        <thead>
          <tr>
            <th scope="col" class="px-6 py-3 text-start font-bold w-28">ID</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-52">Name</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-40">Discount</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-40">Quota</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-40">Used</th>
            <th scope="col" colspan=2 class="px-6 py-3 text-center font-bold w-40">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for voucher in vouchers %}
          <tr class="border-t-2 ">
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ voucher.id_label }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ voucher.voucherName }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ voucher.discountAmount }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ voucher.maxUsage }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ voucher.noOfUsed }}</td>
            <td class="py-4 whitespace-nowrap text-center text-sm font-medium">
              <a href="{% url 'administration:edit_voucher' voucher.voucherId %}"
                class="inline-flex items-center py-2 px-4 text-sm font-bold bg-indigo-600 rounded-md text-white disabled:opacity-50 disabled:pointer-events-none">Edit</a>
            </td>
            <td class="py-4 whitespace-nowrap text-center text-sm font-medium">
              <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="voucherId" value={{ voucher.voucherId }}>
                <button type="submit" class="inline-flex items-center text-sm font-bold text-red-400 rounded-md disabled:opacity-50 disabled:pointer-events-none">Delete</button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}