b4solid/b4solid/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('', include('authentication.urls')),
    path('', include('administration.urls')),
    path('', include('shop.urls')),
    path('', include('payment.urls')),
    path('', include('request.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

b4solid/main/urls.py
from django.urls import include, path
from main.views import main

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
]

b4solid/request/urls.py
from django.urls import path
from request.views import user_requests, add_request, edit_request

app_name = 'request'

urlpatterns = [
    path('user_requests/', user_requests, name='user_requests'),
    path('add_request/', add_request, name='add_request'),
    path('edit_request/<int:id>/', edit_request, name='edit_request'),
]

b4solid/request/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
import requests as rq
import json

def user_requests(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if request.method == 'POST':
        rq.delete('http://aldenluth.fi:8083/requests/' + request.POST['id'])

    user_requests = rq.get('http://aldenluth.fi:8083/requests/user/' + request.session['user'])
    user_requests = user_requests.json()

    context = {}
    context['requests'] = user_requests

    for req in user_requests:
        if req["productId"] is not None:
            req['product_label'] = f'#{req["productId"]:08X}'
        req['id_label'] = f'#{req["id"]:08X}'

    return render(request, 'user_requests.html', context=context)

def add_request(request):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if request.method == 'POST':
        updated_request = request.POST.copy()
        updated_request.update({'username': request.session['user']})

        rq.post(
            url='http://aldenluth.fi:8083/requests',
            data=json.dumps(updated_request),
            headers={'Content-Type': 'application/json'}
        )

        return redirect('request:user_requests')

    return render(request, 'add_request.html')

def edit_request(request, id):
    if 'user' not in request.session:
        return redirect('authentication:login')

    if request.method == 'POST':
        updated_request = request.POST.copy()
        updated_request.update({'username': request.session['user']})

        rq.put(
            url='http://aldenluth.fi:8083/requests/' + str(id),
            data=json.dumps(updated_request),
            headers={'Content-Type': 'application/json'}
        )
        return redirect('request:user_requests')

    req = rq.get('http://aldenluth.fi:8083/requests/' + str(id)).json()
    req['id_label'] = f'#{req["id"]:08X}'

    context = {}
    context['req'] = req

    return render(request, 'edit_request.html', context=context)

b4solid/request/templates/add_request.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="h-screen flex flex-col items-center justify-center">
  <div class="p-6 shadow-2xl rounded-xl flex flex-col items-center justify-center space-y-6 w-1/4">
    <div class="text-4xl font-bold">
      Create Request
    </div>
    <form method="post" class="flex flex-col w-full space-y-4">
      {% csrf_token %}
        <div class="flex flex-col space-y-1">
          <label for="name" class="">Name</label>
          <input type="text" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="name" placeholder="A Very Cool Product" required>
        </div>
        <div class="flex justify-between space-x-3">
          <div class="flex flex-col space-y-1 w-full">
            <label for="harga" class="">Price</label>
            <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="harga" placeholder=0 required>
          </div>
          <div class="flex flex-col space-y-1">
            <label for="stok" class="">Currency</label>
            <select name="currency" class="border-zinc-400 border-2 rounded-md bg-zinc-100" required>
              <option value="IDR">IDR</option>
              <option value="JPY">JPY</option>
              <option value="MYR">MYR</option>
              <option value="USD">USD</option>
            </select>
          </div>
        </div>
        <div class="flex flex-col space-y-1">
          <label for="deskripsi" class="">Description</label>
          <textarea class="border-zinc-400 border-2 rounded-md bg-zinc-100 h-40 resize-none" name="deskripsi" placeholder="Lorem ipsum..."></textarea>
        </div>
        <div class="flex flex-col space-y-1">
          <label for="storeLink" class="">Store URL</label>
          <input type="url" class="border-zinc-400 border-2 rounded-md bg-zinc-100" placeholder="https://example.com" name="storeLink" required>
        </div>
        <div class="flex flex-col space-y-1">
          <label for="imageLink" class="">Image URL</label>
          <input type="url" class="border-zinc-400 border-2 rounded-md bg-zinc-100" placeholder="https://example.com" name="imageLink">
        </div>
      <button class="bg-indigo-600 p-2 mt-8 rounded-md flex items-center justify-center font-bold text-white" type="submit">Create Request</button>
    </form>
  </div>
</div>
{% endblock %}

b4solid/request/templates/edit_request.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="h-screen flex flex-col items-center justify-center">
  <div class="p-6 shadow-2xl rounded-xl flex flex-col items-center justify-center space-y-6 w-1/4">
    <div class="text-4xl font-bold text-center">
      Request<br>{{ req.id_label }}
    </div>
    <form method="post" class="flex flex-col w-full space-y-4">
      {% csrf_token %}
      <div class="flex flex-col space-y-1">
        <label for="name" class="">Name</label>
        <input type="text" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="name"
          value="{{ req.name }}" required>
      </div>
      <div class="flex justify-between space-x-3">
        <div class="flex flex-col space-y-1 w-full">
          <label for="harga" class="">Price</label>
          <input type="number" class="border-zinc-400 border-2 rounded-md bg-zinc-100" name="harga" value="{{ req.harga }}"
            required>
        </div>
        <div class="flex flex-col space-y-1">
          <label for="stok" class="">Currency</label>
          <select name="currency" class="border-zinc-400 border-2 rounded-md bg-zinc-100" required>
            <option value="IDR">IDR</option>
            <option value="JPY">JPY</option>
            <option value="MYR">MYR</option>
            <option value="USD">USD</option>
          </select>
        </div>
      </div>
      <div class="flex flex-col space-y-1">
        <label for="deskripsi" class="">Description</label>
        <textarea class="border-zinc-400 border-2 rounded-md bg-zinc-100 h-40 resize-none" name="deskripsi"
          placeholder="Lorem ipsum...">{% if req.deskripsi %} {{ req.deskripsi }} {% endif %}</textarea>
      </div>
      <div class="flex flex-col space-y-1">
        <label for="storeLink" class="">Store URL</label>
        <input type="url" class="border-zinc-400 border-2 rounded-md bg-zinc-100" value="{{ req.storeLink }}"
          name="storeLink" required>
      </div>
      <div class="flex flex-col space-y-1">
        <label for="imageLink" class="">Image URL</label>
        <input type="url" class="border-zinc-400 border-2 rounded-md bg-zinc-100" placeholder="https://example.com" value="{% if req.imageLink %} {{ req.imageLink }} {% endif %}"
          name="imageLink">
      </div>
      <button class="bg-indigo-600 p-2 mt-8 rounded-md flex items-center justify-center font-bold text-white"
        type="submit">Edit Request</button>
    </form>
  </div>
</div>
{% endblock %}

b4solid/request/templates/user_requests.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="h-screen flex flex-col items-center p-36">
  <p class="text-7xl font-bold">Your Requests</p>
  <div class="flex flex-col items-start mx-10 py-20 w-full space-y-4">
    <a href="{% url 'request:add_request' %}" class="bg-indigo-600 text-white font-bold py-2 px-4 rounded-md">Create Request</a>
    <div class="rounded-md border-2 border-zinc-200 w-full">
      <table class="w-full divide-y divide-zinc-200 table-fixed">
        <thead>
          <tr>
            <th scope="col" class="px-6 py-3 text-start font-bold w-32">ID</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-32">Product ID</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-52">Name</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-36">Price in IDR</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-52">Description</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-36">Store Link</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-36">Image</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-20">Currency</th>
            <th scope="col" class="px-6 py-3 text-start font-bold w-40">Status</th>
            <th scope="col" colspan=2 class="px-6 py-3 text-center font-bold w-40">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for req in requests %}
          <tr class="border-t-2 ">
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ req.id_label }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">
              {% if req.productId %}
                {{ req.product_label }}
              {% else %}
                <span>-</span>
              {% endif %}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ req.name }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden">{{ req.harga }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">
              {% if req.deskripsi %}
                {{ req.deskripsi }}
              {% else %}
                <span>-</span>
              {% endif %}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis text-indigo-600 underline"><a href="{{ req.storeLink }}">{{ req.storeLink }}</a></td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">
              {% if req.imageLink %}
              <a class="text-indigo-600 underline" href="{{ req.imageLink }}">{{ req.imageLink }}</a>
              {% else %}
              <span>-</span>
              {% endif %}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">{{ req.currency }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm border-0 overflow-hidden text-ellipsis">
              {% if req.status == None %}
              <span class="text-yellow-400">Pending</span>
              {% elif req.status == True %}
              <span class="text-emerald-400">Approved</span>
              {% else %}
              <span class="text-red-400">Rejected</span>
              {% endif %}
            </td>
            <td class="py-4 whitespace-nowrap text-center text-sm font-medium">
              {% if req.status == None %}
              <a href="{% url 'request:edit_request' req.id %}"
                class="inline-flex items-center py-2 px-4 text-sm font-bold bg-indigo-600 rounded-md text-white disabled:opacity-50 disabled:pointer-events-none">Edit</a>
              {% endif %}
            </td>
            <td class="py-4 whitespace-nowrap text-center text-sm font-medium">
              {% if req.status == None %}
              <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="id" value={{ req.id }}>
                <button type="submit" class="inline-flex items-center text-sm font-bold text-red-400 rounded-md disabled:opacity-50 disabled:pointer-events-none">Delete</button>
              </form>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}